# Build with:

FROM ubuntu:xenial
ENV SECURITY_UPDATES 2018-02-24
RUN apt-get -y update && apt-get -y install curl software-properties-common
RUN add-apt-repository ppa:hnakamur/golang-1.10
RUN apt-get -y update
RUN apt-get -y install golang-go

ENV GOPATH=/go
RUN mkdir /target
ADD . /go/src/github.com/dotmesh-io/dotmesh/cmd/dm
WORKDIR /go/src/github.com/dotmesh-io/dotmesh/cmd/dm
