# Build with:
FROM ubuntu:bionic
ENV SECURITY_UPDATES 2018-02-20
RUN apt-get -y update && apt-get -y install zfsutils-linux curl golang-1.10-go iproute kmod
ENV PATH=$PATH:/go/bin:/usr/lib/go-1.10/bin
ENV GOPATH=/go
RUN mkdir /target
ADD . /go/src/github.com/dotmesh-io/dotmesh/cmd/dm
WORKDIR /go/src/github.com/dotmesh-io/dotmesh/cmd/dm
