load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.13.0/rules_go-0.13.0.tar.gz"],
    sha256 = "ba79c532ac400cefd1859cbc8a9829346aa69e3b99482cd5a54432092cbc3933",
)

http_archive(
    name = "bazel_gazelle",
    urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/0.13.0/bazel-gazelle-0.13.0.tar.gz"],
    sha256 = "bc653d3e058964a5a26dcad02b6c72d7d63e6bb88d94704990b908a1445b8758",
)

load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")

go_rules_dependencies()

go_register_toolchains()

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")

gazelle_dependencies()

go_repository(
    name = "com_github_apache_thrift",
    commit = "84d6af4cf903571319e0ebddd7beb12bc93fb752",
    importpath = "github.com/apache/thrift",
)

go_repository(
    name = "com_github_aws_aws_sdk_go",
    commit = "e44588ae044e39184d16933dab30c581217ea52c",
    importpath = "github.com/aws/aws-sdk-go",
)

go_repository(
    name = "com_github_blang_semver",
    commit = "60ec3488bfea7cca02b021d106d9911120d25fe9",
    importpath = "github.com/blang/semver",
)

go_repository(
    name = "com_github_coreos_etcd",
    commit = "8825392da229e03467ee2e374ca974c91fd6ee50",
    importpath = "github.com/coreos/etcd",
)

go_repository(
    name = "com_github_davecgh_go_spew",
    commit = "346938d642f2ec3594ed81d874461961cd0faa76",
    importpath = "github.com/davecgh/go-spew",
)

go_repository(
    name = "com_github_eapache_go_resiliency",
    commit = "b86b1ec0dd4209a588dc1285cdd471e73525c0b3",
    importpath = "github.com/eapache/go-resiliency",
)

go_repository(
    name = "com_github_eapache_go_xerial_snappy",
    commit = "bb955e01b9346ac19dc29eb16586c90ded99a98c",
    importpath = "github.com/eapache/go-xerial-snappy",
)

go_repository(
    name = "com_github_eapache_queue",
    commit = "44cc805cf13205b55f69e14bcb69867d1ae92f98",
    importpath = "github.com/eapache/queue",
)

go_repository(
    name = "com_github_go_ini_ini",
    commit = "06f5f3d67269ccec1fe5fe4134ba6e982984f7f5",
    importpath = "github.com/go-ini/ini",
)

go_repository(
    name = "com_github_gogo_protobuf",
    commit = "8d70fb3182befc465c4a1eac8ad4d38ff49778e2",
    importpath = "github.com/gogo/protobuf",
)

go_repository(
    name = "com_github_golang_snappy",
    commit = "d9eb7a3d35ec988b8585d4a0068e462c27d28380",
    importpath = "github.com/golang/snappy",
)

go_repository(
    name = "com_github_gorilla_rpc",
    commit = "5c1378103183095acc1b9289ac1475e3bc1e818e",
    importpath = "github.com/gorilla/rpc",
)

go_repository(
    name = "com_github_howeyc_gopass",
    commit = "f5387c492211eb133053880d23dfae62aa14123d",
    importpath = "github.com/howeyc/gopass",
)

go_repository(
    name = "com_github_inconshreveable_mousetrap",
    commit = "76626ae9c91c4f2a10f34cad8ce83ea42c93bb75",
    importpath = "github.com/inconshreveable/mousetrap",
)

go_repository(
    name = "com_github_jmespath_go_jmespath",
    commit = "0b12d6b5",
    importpath = "github.com/jmespath/go-jmespath",
)

go_repository(
    name = "com_github_klauspost_crc32",
    commit = "cb6bfca970f6908083f26f39a79009d608efd5cd",
    importpath = "github.com/klauspost/crc32",
)

go_repository(
    name = "com_github_mattn_go_runewidth",
    commit = "737072b4e32b7a5018b4a7125da8d12de90e8045",
    importpath = "github.com/mattn/go-runewidth",
)

go_repository(
    name = "com_github_mitchellh_go_homedir",
    commit = "756f7b183b7ab78acdbbee5c7f392838ed459dda",
    importpath = "github.com/mitchellh/go-homedir",
)

go_repository(
    name = "com_github_opentracing_opentracing_go",
    commit = "902ca977fd85455c364050f985eba376b44315f0",
    importpath = "github.com/opentracing/opentracing-go",
)

go_repository(
    name = "com_github_openzipkin_zipkin_go_opentracing",
    commit = "e877b8e9d1069eaedfe4f27e9b6a51cfe20073c9",
    importpath = "github.com/openzipkin/zipkin-go-opentracing",
)

go_repository(
    name = "com_github_pierrec_lz4",
    commit = "ed384a0ef355ee01915875486e8c245ebd567527",
    importpath = "github.com/pierrec/lz4",
)

go_repository(
    name = "com_github_pierrec_xxhash",
    commit = "5a004441f897722c627870a981d02b29924215fa",
    importpath = "github.com/pierrec/xxHash",
)

go_repository(
    name = "com_github_rcrowley_go_metrics",
    commit = "ab2277b1c5d15c3cba104e9cbddbdfc622df5ad8",
    importpath = "github.com/rcrowley/go-metrics",
)

go_repository(
    name = "com_github_shopify_sarama",
    commit = "f4842fc9aec9d1aeb86d0c72c8249ca3e2bbc06e",
    importpath = "github.com/Shopify/sarama",
)

go_repository(
    name = "com_github_spf13_cobra",
    commit = "856b96dcb49d6427babe192998a35190a12c2230",
    importpath = "github.com/spf13/cobra",
)

go_repository(
    name = "com_github_spf13_pflag",
    commit = "dabebe21bf790f782ea4c7bbd2efc430de182afd",
    importpath = "github.com/spf13/pflag",
)

go_repository(
    name = "com_github_ugorji_go",
    commit = "faddd6128c66c4708f45fdc007f575f75e592a3c",
    importpath = "github.com/ugorji/go",
)

go_repository(
    name = "in_gopkg_cheggaaa_pb_v1",
    commit = "d7e6ca3010b6f084d8056847f55d7f572f180678",
    importpath = "gopkg.in/cheggaaa/pb.v1",
)

go_repository(
    name = "org_golang_x_crypto",
    commit = "3c0d69f1777220f1a1d2ec373cb94a282f03eb42",
    importpath = "golang.org/x/crypto",
)

go_repository(
    name = "org_golang_x_net",
    commit = "f09c4662a0bd6bd8943ac7b4931e185df9471da4",
    importpath = "golang.org/x/net",
)

go_repository(
    name = "org_golang_x_sys",
    commit = "c200b10b5d5e122be351b67af224adc6128af5bf",
    importpath = "golang.org/x/sys",
)
